apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-gateway
spec:
  selector:
    app: opsedge360-api-gateway
  ports:
    - port: {{ .Values.service.gatewayPort }}
      targetPort: {{ .Values.service.gatewayPort }}
      name: http
